import Head from "next/head";
import { Inter } from "next/font/google";
import HomeContent from "@/components/content/home";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>
          ReindeerSoft - Lorem, ipsum dolor sit amet consectetur adipisicing
          elit.
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preload" href="../assets/images/home/Liqq.gif" as="image" />
      </Head>
      <HomeContent />
    </>
  );
}
