import llmPromptEngineeringImage from "@/assets/images/llm/llm-prompt-engineering.png";
import { LLMServiceContentType, LLMServiceTitleType } from "@/types/llm.type";

export const title: LLMServiceTitleType = "Prompt Engineering";

export const content: LLMServiceContentType = {
  description: [
    "Crafting effective prompts is crucial for obtaining accurate and context-aware responses from LLMs. Our prompt engineering category focuses on refining the instructions given to the language model to produce desired outputs. Through careful prompt design, optimization, and fine-tuning, we help you improve the quality and relevance of responses generated by LLMs, enhancing the overall performance of your applications.",
  ],
  image: llmPromptEngineeringImage,
};
