import RoboticsAndAutonomy from "@/components/content/robotics-and-autonomy";
import Head from "next/head";

export default function RoboticsAndAnotomyServicesPage() {
  return (
    <>
      <Head>
        <title>
          ReindeerSoft - Lorem, ipsum dolor sit amet consectetur adipisicing
          elit.
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RoboticsAndAutonomy />
    </>
  );
}
